In [1]:
import pandas as pd

In [2]:
import numpy as np 
import matplotlib.pyplot as plt
%matplotlib inline

In [3]:
df = pd.read_csv("survey_results_public.csv")


In [4]:
len(df)

83439

In [5]:
# df = df[["Country", "EdLevel","YearsCodePro","Employment", "ConvertedComp"]]
# df

df.columns

Index(['ResponseId', 'MainBranch', 'Employment', 'Country', 'US_State',
       'UK_Country', 'EdLevel', 'Age1stCode', 'LearnCode', 'YearsCode',
       'YearsCodePro', 'DevType', 'OrgSize', 'Currency', 'CompTotal',
       'CompFreq', 'LanguageHaveWorkedWith', 'LanguageWantToWorkWith',
       'DatabaseHaveWorkedWith', 'DatabaseWantToWorkWith',
       'PlatformHaveWorkedWith', 'PlatformWantToWorkWith',
       'WebframeHaveWorkedWith', 'WebframeWantToWorkWith',
       'MiscTechHaveWorkedWith', 'MiscTechWantToWorkWith',
       'ToolsTechHaveWorkedWith', 'ToolsTechWantToWorkWith',
       'NEWCollabToolsHaveWorkedWith', 'NEWCollabToolsWantToWorkWith', 'OpSys',
       'NEWStuck', 'NEWSOSites', 'SOVisitFreq', 'SOAccount', 'SOPartFreq',
       'SOComm', 'NEWOtherComms', 'Age', 'Gender', 'Trans', 'Sexuality',
       'Ethnicity', 'Accessibility', 'MentalHealth', 'SurveyLength',
       'SurveyEase', 'ConvertedCompYearly'],
      dtype='object')

In [6]:
df["Employment"].value_counts().head(10)

Employed full-time                                      53584
Student, full-time                                      11781
Independent contractor, freelancer, or self-employed     8041
Not employed, but looking for work                       2961
Employed part-time                                       2461
Student, part-time                                       2051
Not employed, and not looking for work                   1228
I prefer not to say                                       890
Retired                                                   326
Name: Employment, dtype: int64

In [7]:
df = df[["Country", "EdLevel","YearsCodePro","Employment","DevType","ConvertedCompYearly"]]

In [8]:
df.head()

Country  \
0                                           Slovakia   
1                                        Netherlands   
2                                 Russian Federation   
3                                            Austria   
4  United Kingdom of Great Britain and Northern I...   

                                             EdLevel YearsCodePro  \
0  Secondary school (e.g. American high school, G...          NaN   
1       Bachelor’s degree (B.A., B.S., B.Eng., etc.)          NaN   
2       Bachelor’s degree (B.A., B.S., B.Eng., etc.)          NaN   
3    Master’s degree (M.A., M.S., M.Eng., MBA, etc.)          NaN   
4    Master’s degree (M.A., M.S., M.Eng., MBA, etc.)           10   

                                          Employment  \
0  Independent contractor, freelancer, or self-em...   
1                                 Student, full-time   
2                                 Student, full-time   
3                                 Employed full-time   
4  Independent contractor, freelancer, or self-em...   

                                             DevType  ConvertedCompYearly  
0                                  Developer, mobile              62268.0  
1                                                NaN                  NaN  
2                                                NaN                  NaN  
3                               Developer, front-end                  NaN  
4  Developer, desktop or enterprise applications;...                  NaN

In [9]:
df.isna().sum()

Country                    0
EdLevel                  313
YearsCodePro           22223
Employment               116
DevType                16955
ConvertedCompYearly    36595
dtype: int64

In [10]:
df = df.dropna()

In [11]:
len(df)

46287

In [12]:
df.head()

Country                                          EdLevel YearsCodePro  \
9    Sweden  Master’s degree (M.A., M.S., M.Eng., MBA, etc.)            4   
11    Spain     Bachelor’s degree (B.A., B.S., B.Eng., etc.)            5   
12  Germany  Master’s degree (M.A., M.S., M.Eng., MBA, etc.)            6   
16   Turkey     Bachelor’s degree (B.A., B.S., B.Eng., etc.)            2   
17   Canada     Bachelor’s degree (B.A., B.S., B.Eng., etc.)            6   

            Employment                                            DevType  \
9   Employed full-time      Data scientist or machine learning specialist   
11  Employed full-time                                Developer, back-end   
12  Employed full-time  Developer, desktop or enterprise applications;...   
16  Employed full-time                              Developer, full-stack   
17  Employed full-time  Developer, front-end;Developer, full-stack;Dev...   

    ConvertedCompYearly  
9               51552.0  
11              46482.0  
12              77290.0  
16              17748.0  
17              46135.0

In [13]:
df = df.rename({"ConvertedCompYearly" : "Salary"},axis=1)

In [14]:
df["DevType"].value_counts().head(20)

Developer, full-stack                                                                                           6423
Developer, back-end                                                                                             4092
Developer, front-end                                                                                            1742
Developer, front-end;Developer, full-stack;Developer, back-end                                                  1615
Developer, full-stack;Developer, back-end                                                                       1380
Developer, mobile                                                                                               1178
Developer, front-end;Developer, full-stack                                                                       790
Other (please specify):                                                                                          648
Developer, desktop or enterprise applications                   

In [15]:
df = df[df["Employment"] == "Employed full-time"] 

In [16]:
len(df)

40187

In [17]:
df["DevType"].value_counts().head(20)

Developer, full-stack                                                                                           5734
Developer, back-end                                                                                             3788
Developer, front-end                                                                                            1573
Developer, front-end;Developer, full-stack;Developer, back-end                                                  1403
Developer, full-stack;Developer, back-end                                                                       1245
Developer, mobile                                                                                               1056
Developer, front-end;Developer, full-stack                                                                       722
Other (please specify):                                                                                          588
Developer, desktop or enterprise applications                   

In [18]:
def shorten_categories(categories,cutoff):
    categorical_map = {}
    for i in range(len(categories)):
        if categories.values[i] >= cutoff:
            categorical_map[categories.index[i]] = categories.index[i]
        else:
            categorical_map[categories.index[i]] = "other"
    return categorical_map

In [19]:
df["Country"].value_counts()

United States of America                                9169
India                                                   3383
Germany                                                 2749
United Kingdom of Great Britain and Northern Ireland    2603
Canada                                                  1552
                                                        ... 
Saint Kitts and Nevis                                      1
Monaco                                                     1
Libyan Arab Jamahiriya                                     1
Somalia                                                    1
Burundi                                                    1
Name: Country, Length: 166, dtype: int64

In [20]:
country_map = shorten_categories(df["Country"].value_counts(),400)
df["Country"] = df["Country"].map(country_map)

In [21]:
df["Country"].value_counts()

other                                                   10721
United States of America                                 9169
India                                                    3383
Germany                                                  2749
United Kingdom of Great Britain and Northern Ireland     2603
Canada                                                   1552
France                                                   1396
Brazil                                                   1340
Spain                                                     890
Netherlands                                               835
Australia                                                 824
Poland                                                    773
Italy                                                     756
Russian Federation                                        741
Sweden                                                    735
Turkey                                                    458
Switzerl

In [22]:
# country_map = shorten_categories(df["Country"].value_counts(),400)
# df["Country"] = df["Country"].map(country_map)

developement_field = shorten_categories(df["DevType"].value_counts(),450)
df["DevType"] = df["DevType"].map(developement_field)


In [23]:
df["DevType"].value_counts()

other                                                                21986
Developer, full-stack                                                 5734
Developer, back-end                                                   3788
Developer, front-end                                                  1573
Developer, front-end;Developer, full-stack;Developer, back-end        1403
Developer, full-stack;Developer, back-end                             1245
Developer, mobile                                                     1056
Developer, front-end;Developer, full-stack                             722
Other (please specify):                                                588
Developer, desktop or enterprise applications                          587
Developer, desktop or enterprise applications;Developer, back-end      552
Developer, embedded applications or devices                            495
Data scientist or machine learning specialist                          458
Name: DevType, dtype: int

In [24]:
for i in range(len(df["DevType"])):
    
    if df["DevType"].values[i] == "Developer, full-stack" :
        df["DevType"].values[i] = "Full-stack Developer"
        
    elif df["DevType"].values[i] == "Developer, front-end;Developer, full-stack;Developer, back-end" :
        df["DevType"].values[i] = "Full-stack Developer"
        
    elif df["DevType"].values[i] == "Developer, full-stack;Developer, back-end" :
        df["DevType"].values[i] = "Full-stack Developer"
        
    elif df["DevType"].values[i] == "Developer, front-end;Developer, full-stack" :
        df["DevType"].values[i] = "Full-stack Developer"
    
    elif df["DevType"].values[i] == "Developer, back-end" :
        df["DevType"].values[i] = "Back-end Developer"
        
    elif df["DevType"].values[i] == "Developer, front-end" :
        df["DevType"].values[i] = "Front-end Developer"
    
    elif df["DevType"].values[i] == "Developer, mobile" :
        df["DevType"].values[i] = "Mobile Developer"
        
    elif df["DevType"].values[i] == "Other (please specify):" :
        df["DevType"].values[i] = "Other"
    
    elif df["DevType"].values[i] == "other" :
        df["DevType"].values[i] = "Other"
        
    elif df["DevType"].values[i] == "Developer, desktop or enterprise applications" :
        df["DevType"].values[i] = "Desktop or Enterprise applications Developer"
    
    elif df["DevType"].values[i] == "Developer, desktop or enterprise applications;Developer, back-end" :
        df["DevType"].values[i] = "Desktop or Enterprise applications Developer"
    
    elif df["DevType"].values[i] == "Developer, embedded applications or devices" :
        df["DevType"].values[i] = "Embedded Applications or devices Developer"
        
    elif df["DevType"].values[i] == "Data scientist or machine learning specialist" :
        df["DevType"].values[i] = "Data scientist or machine learning specialist"

In [25]:
df["DevType"].value_counts()

Other                                            22574
Full-stack Developer                              9104
Back-end Developer                                3788
Front-end Developer                               1573
Desktop or Enterprise applications Developer      1139
Mobile Developer                                  1056
Embedded Applications or devices Developer         495
Data scientist or machine learning specialist      458
Name: DevType, dtype: int64

In [26]:
df = df[df["Salary"] <250000]
df = df[df["Salary"] >10000]

In [27]:
len(df)

35042

In [28]:
df.head()

Country                                          EdLevel YearsCodePro  \
9    Sweden  Master’s degree (M.A., M.S., M.Eng., MBA, etc.)            4   
11    Spain     Bachelor’s degree (B.A., B.S., B.Eng., etc.)            5   
12  Germany  Master’s degree (M.A., M.S., M.Eng., MBA, etc.)            6   
16   Turkey     Bachelor’s degree (B.A., B.S., B.Eng., etc.)            2   
17   Canada     Bachelor’s degree (B.A., B.S., B.Eng., etc.)            6   

            Employment                                        DevType   Salary  
9   Employed full-time  Data scientist or machine learning specialist  51552.0  
11  Employed full-time                             Back-end Developer  46482.0  
12  Employed full-time   Desktop or Enterprise applications Developer  77290.0  
16  Employed full-time                           Full-stack Developer  17748.0  
17  Employed full-time                           Full-stack Developer  46135.0

In [29]:
df["YearsCodePro"].unique()

array(['4', '5', '6', '2', '18', '21', '16', '10', 'Less than 1 year',
       '3', '15', '1', '12', '8', '17', '14', '26', '34', '11', '25',
       '24', '7', '22', '13', '9', '20', '23', '39', '27', '30', '19',
       '35', '33', '37', '43', '40', '29', '38', '31', '42', '28', '46',
       '32', '36', '47', '45', '44', '41', 'More than 50 years', '50',
       '49', '48'], dtype=object)

In [30]:
def clean_experience(x):
    if x ==  'More than 50 years':
        return 50
    if x == 'Less than 1 year':
        return 0.5
    return float(x)

df['YearsCodePro'] = df['YearsCodePro'].apply(clean_experience)

In [31]:
df["YearsCodePro"].unique()

array([ 4. ,  5. ,  6. ,  2. , 18. , 21. , 16. , 10. ,  0.5,  3. , 15. ,
        1. , 12. ,  8. , 17. , 14. , 26. , 34. , 11. , 25. , 24. ,  7. ,
       22. , 13. ,  9. , 20. , 23. , 39. , 27. , 30. , 19. , 35. , 33. ,
       37. , 43. , 40. , 29. , 38. , 31. , 42. , 28. , 46. , 32. , 36. ,
       47. , 45. , 44. , 41. , 50. , 49. , 48. ])

In [32]:
df["EdLevel"].unique()

array(['Master’s degree (M.A., M.S., M.Eng., MBA, etc.)',
       'Bachelor’s degree (B.A., B.S., B.Eng., etc.)',
       'Some college/university study without earning a degree',
       'Professional degree (JD, MD, etc.)',
       'Other doctoral degree (Ph.D., Ed.D., etc.)', 'Something else',
       'Primary/elementary school', 'Associate degree (A.A., A.S., etc.)',
       'Secondary school (e.g. American high school, German Realschule or Gymnasium, etc.)'],
      dtype=object)

In [33]:
def clean_education(x):
    if 'Bachelor’s degree' in x:
        return 'Bachelor’s degree'
    if 'Master’s degree' in x:
        return 'Master’s degree'
    if 'Professional degree' in x or 'Other doctoral' in x:
        return 'Post grad'
    return 'Less than a Bachelors'

df['EdLevel'] = df['EdLevel'].apply(clean_education)

In [34]:
df["EdLevel"].unique()

array(['Master’s degree', 'Bachelor’s degree', 'Less than a Bachelors',
       'Post grad'], dtype=object)

In [35]:
df["Country"].unique()

array(['Sweden', 'Spain', 'Germany', 'Turkey', 'Canada', 'France',
       'Switzerland',
       'United Kingdom of Great Britain and Northern Ireland',
       'Russian Federation', 'Israel', 'other',
       'United States of America', 'Brazil', 'Italy', 'Netherlands',
       'Poland', 'Australia', 'India', 'Norway'], dtype=object)

In [36]:
df["DevType"].unique()

array(['Data scientist or machine learning specialist',
       'Back-end Developer',
       'Desktop or Enterprise applications Developer',
       'Full-stack Developer', 'Other',
       'Embedded Applications or devices Developer', 'Mobile Developer',
       'Front-end Developer'], dtype=object)

In [37]:
from sklearn.preprocessing import LabelEncoder
le_education = LabelEncoder()
df['EdLevel'] = le_education.fit_transform(df['EdLevel'])
df["EdLevel"].unique()

array([2, 0, 1, 3])

In [38]:
le_country = LabelEncoder()
df['Country'] = le_country.fit_transform(df['Country'])
df["Country"].unique()


array([13, 12,  4, 15,  2,  3, 14, 16, 11,  6, 18, 17,  1,  7,  8, 10,  0,
        5,  9])

In [39]:
le_devtype = LabelEncoder()
df["DevType"] = le_devtype.fit_transform(df["DevType"])
df["DevType"].unique()

array([1, 0, 2, 5, 7, 3, 6, 4])

In [40]:
df.head()

Country  EdLevel  YearsCodePro          Employment  DevType   Salary
9        13        2           4.0  Employed full-time        1  51552.0
11       12        0           5.0  Employed full-time        0  46482.0
12        4        2           6.0  Employed full-time        2  77290.0
16       15        0           2.0  Employed full-time        5  17748.0
17        2        0           6.0  Employed full-time        5  46135.0

In [41]:
df = df.drop("Employment",axis=1)

In [42]:
df.head()

Country  EdLevel  YearsCodePro  DevType   Salary
9        13        2           4.0        1  51552.0
11       12        0           5.0        0  46482.0
12        4        2           6.0        2  77290.0
16       15        0           2.0        5  17748.0
17        2        0           6.0        5  46135.0

In [43]:
x = df.drop("Salary",axis=1)
y = df["Salary"]

In [44]:
np.random.seed(0)

from sklearn.model_selection import train_test_split

x_train , x_test , y_train , y_test = train_test_split(x,y,test_size=0.2)

from sklearn.ensemble import RandomForestRegressor

model = RandomForestRegressor(n_estimators=30)

model.fit(x_train,y_train)

model.score(x_test,y_test)


# for i in range(10,100,10):
#     model = RandomForestRegressor(n_estimators=i)
    
#     model.fit(x_train,y_train)
    
#     print(i)
#     print(model.score(x_test,y_test))

0.5520163212506971

In [45]:
y_pred = model.predict(x)
y_pred

array([ 54344.4       ,  37770.94166667,  87002.5075    , ...,
       129165.76179684,  81204.10813851,  17830.93238095])

In [46]:
from sklearn.metrics import mean_squared_error, mean_absolute_error

error = np.sqrt(mean_squared_error(y, y_pred))
error

28641.895641289495

In [47]:
# country, edlevel, yearscode
X = np.array([["United States of America", 'Master’s degree', 15 ,"Data scientist or machine learning specialist"]])
X


array([['United States of America', 'Master’s degree', '15',
        'Data scientist or machine learning specialist']], dtype='<U45')

In [48]:
X[:, 0] = le_country.transform(X[:,0])
X[:, 1] = le_education.transform(X[:,1])
X[:,3] = le_devtype.transform(X[:,3])
X = X.astype(float)
X

array([[17.,  2., 15.,  1.]])

In [49]:
import pickle

In [50]:
data = {"model": model, "le_country": le_country, "le_education": le_education, "le_devtype" : le_devtype}
with open('saved_steps.pkl', 'wb') as file:
    pickle.dump(data, file)


In [51]:
with open('saved_steps.pkl', 'rb') as file:
    data = pickle.load(file)

regressor_loaded = data["model"]
le_country = data["le_country"]
le_education = data["le_education"]
le_devtype = data["le_devtype"]


In [52]:
y_pred = model.predict(X)
y_pred


E:\machinelearning\salaryPrediction\env\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(


array([167022.30952381])